### ISSUE TITLE
can't compile on Linux

### ISSUE THREAD

**Issue by tissatussa** [SnowballSH/Avalanche#22]
i get this error :

```
$ zig build -Drelease-fast 
/home/roelof/Compiled/Avalanche/build.zig:108:9: error: no field named 'use_stage1' in struct 'build.LibExeObjStep'
    exe.use_stage1 = true;
        ^~~~~~~~~~
/snap/zig/6170/lib/std/build/LibExeObjStep.zig:1:1: note: struct declared here
const builtin = @import("builtin");
^~~~~
referenced by:
    runBuild: /snap/zig/6170/lib/build_runner.zig:228:22
    usage__anon_5102: /snap/zig/6170/lib/build_runner.zig:238:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

```

is it easy to fix ?
i'm not familiar woth Zig ..

[ using Xubuntu 22.04 ]

**Comment by SnowballSH** [comment]
Hi,
Your version of zig is too new. Zig recently removed support for stage1, but Avalanche only works on stage1. Currently Avalanche is only tested on zig 0.10.0.
Thank you!

**Comment by tissatussa** [comment]
sorry for this message in a closed Issue, i'm not familiar with Zig .. however on their site i see other versions to download .. also 0.10.0 .. should i first just uninstall my current version ? Another way to (also) have 0.10.0 on my Xubuntu ? In Python we can use an 'env'(ironment).

**Comment by SnowballSH** [comment]
Hi,
I think what you mean is a version manager to switch between versions of zig.

https://github.com/marler8997/zigup
This might be what you are looking for.
Thank you for your interest.

**Comment by SnowballSH** [comment]
NB. You don't have to build zigup yourself. Go to the release page and you shall see binaries for your system.
